apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    texas.nais.io/enabled: "true"
  name: oebs-digihot-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  envFrom:
    - secret: oebs-digihot-api
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 11
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    requests:
      cpu: 40m
      memory: 512Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  accessPolicy:
    inbound:
      rules:
        - application: saas-proxy
          namespace: platforce
          cluster: prod-gcp
  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-digihot-api.intern.nav.no"
    - "https://oebs-digihot-api.prod-fss-pub.nais.io"